micronaut:
  application:
    name: market-data-service
  server:
    host: 0.0.0.0
    port: 8081

grpc:
  server:
    port: 50052       # port, na którym działa gRPC

twelvedata:
  base-url: ${TWELVEDATA_BASE_URL:https://api.twelvedata.com}
  apiKey: ${TWELVEDATA_API_KEY}

datasources:
  default:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 10  # max równoczesnych połączeń z puli
    minimumIdle: 2
    idleTimeout: 30000   # ms
    connectionTimeout: 30000
    maxLifetime: 1800000 # ms

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update