micronaut:
  application:
    name: market-data-service
  server:
    port: 8081

grpc:
  server:
    port: 50052

redis:
  uri: redis://localhost:6379

datasources:
  default:
    url: jdbc:postgresql://ep-royal-star-ahw87sxu-pooler.c-3.us-east-1.aws.neon.tech/found?sslmode=require&channelBinding=require
    username: XXXXXXXXXX
    password: XXXXXXXX
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 10  # max równoczesnych połączeń z puli
    minimumIdle: 2
    idleTimeout: 30000   # ms
    connectionTimeout: 30000
    maxLifetime: 1800000 # ms

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update