micronaut:
  application:
    name: market-data-service
  server:
    port: 8081

grpc:
  server:
    port: 50052

redis:
  uri: redis://localhost:6379

#ce7d183bf8314c059f7117d2ff75a8a4
#2615885015284d6d97d8c2c6da7a3d38
 # 1500834ed5184823a6f50559c0c091e5
finnhub:
  token: 2615885015284d6d97d8c2c6da7a3d38

datasources:
  default:
    url: jdbc:postgresql://ep-royal-star-ahw87sxu-pooler.c-3.us-east-1.aws.neon.tech/found?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_EUzkDuIs76ae
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 10  # max równoczesnych połączeń z puli
    minimumIdle: 2
    idleTimeout: 30000   # ms
    connectionTimeout: 30000
    maxLifetime: 1800000 # ms

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update