micronaut:
  application:
    name: market-data-service
  server:
    host: 0.0.0.0
    port: 8084

datasources:
  default:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

grpc:
  server:
    port: 50054       # port, na którym działa gRPC

twelvedata:
  base-url: ${TWELVEDATA_BASE_URL:https://api.twelvedata.com}
  apikey: ${TWELVEDATA_API_KEY}