micronaut:
  application:
    name: market-data-service
  server:
    port: 8084

datasources:
  default:
    url: jdbc:postgresql://ep-royal-star-ahw87sxu-pooler.c-3.us-east-1.aws.neon.tech/found?sslmode=require
    username: neondb_owner
    password: npg_5QLOhgFeyRE7
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

kafka:
  bootstrap:
    servers: "localhost:9092"
  producer:
    value-serializer: io.micronaut.configuration.kafka.serde.JsonSerializer

grpc:
  server:
    port: 50054

twelvedata:
  base-url: https://api.twelvedata.com
  apikey: ce7d183bf8314c059f7117d2ff75a8a4