micronaut:
  application:
    name: market-data-service
  server:
    port: 8084

datasources:
  default:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

kafka:
  bootstrap:
    servers: "localhost:9092"
  producer:
    value-serializer: io.micronaut.configuration.kafka.serde.JsonSerializer

grpc:
  server:
    port: 50054
  channels:
    marketdata:
      address: "localhost:50052"
      plaintext: true

twelvedata:
  base-url: ${TWELVEDATA_BASE_URL:https://api.twelvedata.com}
  apikey: ${TWELVEDATA_API_KEY}