apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common/postgres-deployment.yaml
  - common/redis-deployment.yaml
  - common/rabbitmq-deployment.yaml
  - reservation-service/deployment.yaml
  - notification-service/deployment.yaml
  - analytics-service/deployment.yaml
  - api-server/deployment.yaml
namespace: smart-reservation