micronaut:
  application:
    name: market-itemPrices-service
  server:
    port: 8083

datasources:
  default:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 10  # max równoczesnych połączeń z puli
    minimumIdle: 2
    idleTimeout: 30000   # ms
    connectionTimeout: 30000
    maxLifetime: 1800000 # ms

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

kafka:
  bootstrap:
    servers: "localhost:9092"
  producer:
    value-serializer: io.micronaut.configuration.kafka.serde.JsonSerializer

redis:
  uri: redis://localhost:6379

grpc:
  server:
    port: 50053
  channels:
    marketdata:
      address: "localhost:50052"
      plaintext: true