micronaut:
  application:
    name: market-itemPrices-service
  server:
    host: 0.0.0.0
    port: 8083

datasources:
  default:
    url: jdbc:postgresql://ep-royal-star-ahw87sxu-pooler.c-3.us-east-1.aws.neon.tech/found?sslmode=require&channelBinding=require
    username: XXXXXXX
    password: XXXXXXX
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 10  # max równoczesnych połączeń z puli
    minimumIdle: 2
    idleTimeout: 30000   # ms
    connectionTimeout: 30000
    maxLifetime: 1800000 # ms

grpc:
  server:
    port: 50053       # port, na którym działa gRPC