micronaut:
  application:
    name: market-data-service
  server:
    port: 8083

grpc:
  server:
    port: 50053

twelvedata:
  base-url: https://api.twelvedata.com
  apikey: ce7d183bf8314c059f7117d2ff75a8a4