micronaut:
  application:
    name: api-server
  server:
    host: 0.0.0.0
    port: 8080

endpoints:
  all:
    enabled: true

grpc:
  channels:
    marketdata:
      address: "localhost:50052"
      plaintext: true
    portfolio:
      address: "localhost:50053"
      plaintext: true
    transaction:
      address: "localhost:50054"
      plaintext: true
