micronaut:
  application:
    name: api-server


grpc:
  channels:
    auth:
      address: "localhost:50050"
      plaintext: true
    market-data:
      address: "localhost:50052"
      plaintext: true
    portfolio:
      address: "localhost:50053"
      plaintext: true
    transaction:
      address: "localhost:50054"
      plaintext: true
    historical-data:
      address: "localhost:50055"
      plaintext: true
